name: Android Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Lint check
        run: ./gradlew lint

      - name: Ktlint check
        run: ./gradlew ktlintcheck

      - name: Run test
        run: ./gradlew test

      - name: Build
        run: ./gradlew build
